/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package view.example.json;

import io.dropwizard.configuration.EnvironmentVariableSubstitutor;
import io.dropwizard.configuration.SubstitutingSourceProvider;
import io.dropwizard.core.Application;
import io.dropwizard.core.setup.Bootstrap;
import io.dropwizard.core.setup.Environment;
import io.dropwizard.views.common.ViewBundle;
import ru.vyarus.dropwizard.guice.GuiceBundle;
import view.example.json.resources.PersonModule;

public class JsonEgApplication extends Application<JsonEgConfiguration> {

    public static void main(String[] args) throws Exception {
        new JsonEgApplication().run(args);
    }

    @Override
    public String getName() {
        return "view-example-json";
    }

    @Override
    public void initialize(Bootstrap<JsonEgConfiguration> bootstrap) {

        bootstrap.setConfigurationSourceProvider(
            new SubstitutingSourceProvider(bootstrap.getConfigurationSourceProvider(),
                new EnvironmentVariableSubstitutor(false)
            )
        );

        GuiceBundle guiceBundle = GuiceBundle.builder()
            .modules(
                new PersonModule()
            ).build();
        bootstrap.addBundle(guiceBundle);

        bootstrap.addBundle(new ViewBundle<>());
    }

    @Override
    public void run(JsonEgConfiguration configuration, Environment environment) throws Exception {

    }
}
