/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package view.example.html;

import io.dropwizard.configuration.EnvironmentVariableSubstitutor;
import io.dropwizard.configuration.SubstitutingSourceProvider;
import io.dropwizard.core.Application;
import io.dropwizard.core.setup.Bootstrap;
import io.dropwizard.core.setup.Environment;
import io.dropwizard.views.common.ViewBundle;
import ru.vyarus.dropwizard.guice.GuiceBundle;
import view.example.html.resources.PersonModule;

public class HtmlEgApplication extends Application<HtmlEgConfiguration> {

  public static void main(String[] args) throws Exception {
    new HtmlEgApplication().run(args);
  }

  @Override
  public String getName() {
    return "view-example-html";
  }

  @Override
  public void initialize(Bootstrap<HtmlEgConfiguration> bootstrap) {

    bootstrap.setConfigurationSourceProvider(
        new SubstitutingSourceProvider(bootstrap.getConfigurationSourceProvider(),
            new EnvironmentVariableSubstitutor(false)
        )
    );

    GuiceBundle guiceBundle = GuiceBundle.builder()
        .modules(
            new PersonModule()
        ).build();
    bootstrap.addBundle(guiceBundle);

    bootstrap.addBundle(new ViewBundle<>());
  }

  @Override
  public void run(HtmlEgConfiguration configuration, Environment environment) throws Exception {

  }
}
